<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-31QF9S5P" failures="1" tests="5" name="FireFoxTest" time="4.909" errors="0" timestamp="2022-03-10T20:23:34 IST">
  <testcase classname="acti123.TestClassNG" name="@AfterMethod logOutfromActiTime" time="0.086">
    <failure type="java.lang.IllegalArgumentException" message="Cannot format given Object as a Date">
      <![CDATA[java.lang.IllegalArgumentException: Cannot format given Object as a Date
at java.base/java.text.DateFormat.format(DateFormat.java:342)
at java.base/java.text.Format.format(Format.java:159)
at utils.Utility.captureScreenshot(Utility.java:50)
at acti123.TestClassNG.logOutfromActiTime(TestClassNG.java:126)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod logOutfromActiTime -->
  <testcase classname="acti123.TestClassNG" name="@BeforeMethod logInToActiTime" time="-1.646924014978E9">
    <skipped/>
  </testcase> <!-- @BeforeMethod logInToActiTime -->
  <testcase classname="acti123.TestClassNG" name="@AfterMethod logOutfromActiTime" time="-1.646924014982E9">
    <skipped/>
  </testcase> <!-- @AfterMethod logOutfromActiTime -->
  <testcase classname="acti123.TestClassNG" name="@AfterClass clearPOMObject" time="-1.646924014984E9">
    <skipped/>
  </testcase> <!-- @AfterClass clearPOMObject -->
  <testcase classname="acti123.TestClassNG" name="@AfterTest closeBrowser" time="-1.646924014985E9">
    <skipped/>
  </testcase> <!-- @AfterTest closeBrowser -->
  <testcase classname="acti123.TestClassPrac" name="test1111" time="0.001"/>
  <testcase classname="acti123.TestClassPrac" name="test2222" time="0.0"/>
  <testcase classname="acti123.TestClassPrac" name="test3333" time="0.0"/>
  <testcase classname="acti123.TestClassNG" name="verifyTask" time="0.312">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at acti123.TestClassNG.verifyTask(TestClassNG.java:117)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verifyTask -->
  <testcase classname="acti123.TestClassNG" name="verifyTime" time="0.0">
    <skipped/>
  </testcase> <!-- verifyTime -->
</testsuite> <!-- FireFoxTest -->
